# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that.
# This file is *NOT* reloaded automatically when you use 'bundle exec jekyll serve'.
# If you change this file, please restart the server process.

# Site settings
# are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog

title: Aurélie Fréchet - dataRtist
email: aurelie.frechet@gmail.com #this is also the email contact forms will go to
description: "Développeuse freelance R/RShiny"
author: Aurélie Fréchet
# logo:     #optional, defaults to site title
  # path: assets\img\clients\creative-market.jpg
  # height: 60 #height in px, defaults to 52px

locale: "fr-FR" # Available languages: "en-US" (English) and "fr-FR" (French) - See _data/sitetext.yml

analytics:
  google: #Google Analytics tracking code here

forms:
  unstatic: 795df5453ac9b773135a5252f32c830fc36b89b4 #(https://un-static.com/how-to/add-github-pages-contact-form)

collections:
  portfolio:
    output: false
    defaults:
      - scope:
          path: "_portfolio"
          type: "portfolio"
        values:
          layout: "portfolio"

markdown: kramdown
